libraryPath = '/usr/lib'
sources = ['../src/Sequence.cpp', '../src/Sequence.hpp', '../src/Graph.hpp', \
    '../src/Graph.cpp']
test_sources = ['main-test.cpp','Sequence-test.cpp', 'Graph-test.cpp', \
    'SmallSequencesFixture.hpp']
test_sources.extend(sources)

test = Environment()

test.Append(LIBPATH = [libraryPath])
test.Append(LINKFLAGS = ['-lboost_unit_test_framework','-std=c++11'])


test.Append(CCFLAGS = ['-g', '-O0', '-std=c++11', '-Werror'])
mainTest = test.Program(target='main-test', source=test_sources)
# Depend on the runner to ensure that it's built before running it.
mainTestAlias = Alias('test', [mainTest], mainTest[0].path)
# Simply required.  Without it, 'test' is never considered out of date.
AlwaysBuild(mainTestAlias)
