libraryPath = '/usr/lib'
sources = ['Sequence.cpp', 'Sequence.hpp',
    'Graph.hpp', 'Graph.cpp',
    'Path.hpp', 'Path.cpp']
prod = Environment()
prod.Append(CCFLAGS = ['-O3','-std=c++11','-Werror'])
prod.Append(CFLAGS = ['-std=c++11','-Werror'])
prod.Append(LINKFLAGS = ['-std=c++11','-Werror'])
prod.Append(LIBPATH = [libraryPath])
mainSources = sources
mainSources.append('FireflyAssembler-main.cpp')
program = prod.Program('FireflyAssembler', mainSources)
Default(program)
