Import('mode')
libraryPaths = [ '/usr/lib', '/usr/local/lib' ]
sources = ['Sequence.cpp', \
    'Graph.cpp', \
    'Path.cpp', \
    'MeanOverlap.cpp', \
    'N50Rating.cpp', \
    'GreedyPathFinder.cpp', \
    'LocalSearchPathFinder.cpp', \
    'FireflyPathFinder.cpp', \
    'HammingDistance.cpp']
env = Environment()

ccFlags = ['-std=c++11','-Werror']
if mode == 'debug':
    ccFlags.extend(['-O0','-g'])
else:
    ccFlags.append('-O3')
env.Append(CCFLAGS = ccFlags)
env.Append(CFLAGS = ['-std=c++11','-Werror'])
env.Append(LINKFLAGS = ['-std=c++11','-Werror'])
env.Append(LIBPATH = libraryPaths)
mainSources = sources
mainSources.append('FireflyAssembler-main.cpp')
program = env.Program('FireflyAssembler', mainSources)
Default(program)
