#!/bin/sh
set -e
set -x
cd /fslhome/dhaskin/FireflyAssembler/resources/lactobacillus_acidophilus
for input in 500 1000 1500 2000 2500 3000 3500 4000 4500 5000 5500 6000 6500 7000 7500 8000 8500 9000 9500 10000
do
    file=5x_coverage_${input}.reads.fasta
    python ../sim-reads.py ./CP002559.fna ./${file} 5 ${input}
    for strategy in firefly greedy localsearch
    do
        cat > ${strategy}_${input}_batch.sh << BATCH
#!/bin/bash

#Submit this script with: sbatch thefilename

#SBATCH --time=168:00:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=1024M   # memory per CPU core
#SBATCH -J "lacto_${input}_${strategy}"   # job name
#SBATCH --mail-user=djhaskin987@gmail.com   # email address
#SBATCH --mail-type=END
#SBATCH --output=/fslhome/dhaskin/FireflyAssembler/resources/lactobacillus_acidophilus/${strategy}_${input}.out
#SBATCH --error=/fslhome/dhaskin/FireflyAssembler/resources/lactobacillus_acidophilus/${strategy}_${input}.err

set -x

cd /fslhome/dhaskin/FireflyAssembler/resources/lactobacillus_acidophilus
export PATH="/fslgroup/fslg_genome/software/bin:${HOME}/bin:${HOME}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HOME}/usr/lib64:${HOME}/usr/lib:${LD_LIBRARY_PATH}"
export LANG="en_US.UTF-8"
export LOCALE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export PYTHONPATH="/fslgroup/fslg_genome/software/lib64/python2.6/site-packages/"

echo "Running on ${input}..."
echo "Using strategy ${strategy}..."
echo "Getting time..."
/fslhome/dhaskin/FireflyAssembler/release-main/FireflyAssembler -p ${strategy} ./${file} ./contigs_${strategy}_${input}.fasta
exit 0
BATCH
        sbatch ${strategy}_${input}_batch.sh
    done
done
